sudo: required

language: python

before_install:
- pip install sphinx

script:
  - cd doc
  - sphinx-apidoc -eo source ..
  - sphinx-build -b html . ../html
  - cd ../html
  - touch .nojekyll

deploy:
  provider: pages
  local-dir: html
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  target-branch: gh-pages
  keep-history: false
  on:
    branch: master
